const { ChannelType, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const db=require('./database');const config=require('./config');
function renderName(template,member){return template.replaceAll('{user}',member.displayName).replaceAll('{username}',member.user.username).slice(0,100);}
async function logEvent(guild,title,description){const cfg=db.getGuild(guild.id);if(!cfg?.log_channel_id)return;const c=guild.channels.cache.get(cfg.log_channel_id);if(!c?.isTextBased())return;await c.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(description).setTimestamp()]}).catch(()=>{});}
function roomPermissions(guild,ownerId){return[{id:guild.roles.everyone.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect]},{id:ownerId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak,PermissionFlagsBits.ManageChannels]}];}
async function createTextChannel(guild,category,member){return guild.channels.create({name:`text-${member.user.username}`.slice(0,100),type:ChannelType.GuildText,parent:category.id,reason:'Cukur Voice private room text',permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:member.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}]});}
async function createTemp(newState,cfg){const member=newState.member,category=newState.guild.channels.cache.get(cfg.category_id);if(!category)return null;const ch=await newState.guild.channels.create({name:renderName(cfg.room_template||config.defaults.roomTemplate,member),type:ChannelType.GuildVoice,parent:category.id,userLimit:cfg.default_limit||0,bitrate:Math.min(cfg.default_bitrate||64000,newState.guild.maximumBitrate||64000),rtcRegion:cfg.default_region||null,reason:`Cukur Voice room for ${member.user.tag}`,permissionOverwrites:roomPermissions(newState.guild,member.id)});let text=null;if(cfg.text_enabled)text=await createTextChannel(newState.guild,category,member).catch(()=>null);db.addTemp(ch.id,newState.guild.id,member.id,cfg.generator_id,text?.id||null);if(cfg.voice_role_id){const role=newState.guild.roles.cache.get(cfg.voice_role_id);if(role?.editable)await member.roles.add(role,'Cukur Voice temporary room').then(()=>db.addRoleAssignment(ch.id,member.id,role.id)).catch(()=>{});}try{await member.voice.setChannel(ch,'Cukur Voice room created');}catch(e){await deleteTemp(ch,'Failed to move member into room');throw e;}await logEvent(newState.guild,'Temporary room created',`${member} created ${ch}${text?` with ${text}`:''}.`);return ch;}
async function deleteTemp(channel,reason='Cukur Voice room deleted'){const temp=db.getTemp(channel.id);if(!temp)return false;const guild=channel.guild;for(const a of db.listRoleAssignments(channel.id)){const m=guild.members.cache.get(a.user_id),r=guild.roles.cache.get(a.role_id);if(m&&r)await m.roles.remove(r,'Cukur Voice room cleanup').catch(()=>{});}const text=temp.text_channel_id?guild.channels.cache.get(temp.text_channel_id):null;db.removeTemp(channel.id);if(text)await text.delete(reason).catch(()=>{});await channel.delete(reason).catch(()=>{});await logEvent(guild,'Temporary room deleted',`${channel.name} was deleted. Reason: ${reason}.`);return true;}
async function syncOwner(channel,oldOwnerId,newOwner){if(!newOwner)return false;const temp=db.getTemp(channel.id);if(!temp)return false;db.addTemp(channel.id,channel.guild.id,newOwner.id,temp.generator_id,temp.text_channel_id);await channel.permissionOverwrites.edit(newOwner.id,{ViewChannel:true,Connect:true,Speak:true,ManageChannels:true}).catch(()=>{});if(temp.text_channel_id){const text=channel.guild.channels.cache.get(temp.text_channel_id);if(text){await text.permissionOverwrites.edit(newOwner.id,{ViewChannel:true,SendMessages:true,ReadMessageHistory:true}).catch(()=>{});if(oldOwnerId)await text.permissionOverwrites.delete(oldOwnerId).catch(()=>{});}}const cfg=db.getGuild(channel.guild.id);if(cfg?.voice_role_id){const role=channel.guild.roles.cache.get(cfg.voice_role_id),old=channel.guild.members.cache.get(oldOwnerId);if(old&&role)await old.roles.remove(role,'Cukur Voice ownership transfer').catch(()=>{});if(role?.editable)await newOwner.roles.add(role,'Cukur Voice ownership transfer').then(()=>db.addRoleAssignment(channel.id,newOwner.id,role.id)).catch(()=>{});}await logEvent(channel.guild,'Room ownership transferred',`${newOwner} is now the owner of ${channel}.`);return true;}
async function transferOwner(channel,oldOwnerId,newOwner){const temp=db.getTemp(channel.id);if(!temp||!newOwner)return false;if(oldOwnerId&&temp.owner_id!==oldOwnerId&&temp.owner_id!==newOwner.id)return false;return syncOwner(channel,oldOwnerId,newOwner);}
async function cleanup(channel){const temp=db.getTemp(channel.id);if(!temp||channel.members.size>0)return;await deleteTemp(channel,'Room became empty');}
async function reconcile(client){for(const cfg of db.listGuilds()){const guild=client.guilds.cache.get(cfg.guild_id);if(!guild)continue;for(const temp of db.listTemps(cfg.guild_id)){const ch=guild.channels.cache.get(temp.channel_id);if(!ch){db.removeTemp(temp.channel_id);continue;}if(ch.members.size===0)await deleteTemp(ch,'Stale room cleanup');}}}
async function handleVoiceState(oldState,newState){if(oldState.channelId===newState.channelId)return;const guild=newState.guild||oldState.guild,cfg=db.getGuild(guild.id);if(!cfg)return;if(newState.channelId&&(newState.channelId===cfg.generator_id||newState.channelId===cfg.waiting_room_id)&&!newState.member.user.bot)await createTemp(newState,cfg);if(oldState.channelId){const old=oldState.guild.channels.cache.get(oldState.channelId);if(old){const temp=db.getTemp(old.id);if(temp&&temp.owner_id===oldState.member.id&&old.members.size>0)await transferOwner(old,oldState.member.id,old.members.first());await cleanup(old);}}}
module.exports={handleVoiceState,createTemp,deleteTemp,transferOwner,logEvent,reconcile};